### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [derivator/tafkars#8]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by derivator** [comment]
Yeah I should probably add the file instead of just setting it in `Cargo.toml`. And I'm a big fan of the GPL, but `tafkars` is based heavily on [`roux`](https://github.com/halcyonnouveau/roux) which is MIT, so I chose to stick with that.
